dist: focal

addons:
  apt:
    update:
      true
    sources:
    - deadsnakes
    packages:
    - inkscape
    - nodejs
    - haxe
    - neko
    - python3
    - python3-pip
    - python3-setuptools

install:
  # fonts for svg to png conversion
  - wget https://noto-website-2.storage.googleapis.com/pkgs/NotoSans-hinted.zip
  - unzip NotoSans-hinted.zip
  - mkdir -p ~/.fonts
  - cp NotoSans-Regular.ttf ~/.fonts
  - fc-cache -f -v
  # checkout HaxeManual
  - git clone https://github.com/HaxeFoundation/HaxeManual.git manual
  # update pip
  - python3.11 -m pip install pip
  # install awscli
  - pip3 install --user awscli
  - pip3 install rsa
  - aws --version
  # install haxelibs
  - yes | haxelib install all
  # get hxnodejs from git, haxelib's is outdated
  - haxelib git hxnodejs https://github.com/HaxeFoundation/hxnodejs.git
  # get markdown from git, haxelib's is outdated
  - haxelib git markdown https://github.com/HaxeFoundation/haxe-markdown.git
  # get tink_syntaxhub from git, fix compile error with haxe dev
  - haxelib git tink_syntaxhub https://github.com/haxetink/tink_syntaxhub.git
  # Get vscode-textmate
  - npm install

script:
  - haxe generate.hxml

deploy:
  provider: script
  script: haxe deploy.hxml
  on:
    all_branches: true
    condition: $TRAVIS_BRANCH =~ ^feature/haxe4|staging|master$ && $TRAVIS_EVENT_TYPE != "cron"
  skip_cleanup: true
